// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export X := Rectangle {
//       ><warning{':=' to declare a component is deprecated. The new syntax declare components with 'component MyComponent {'. Read the documentation for more info}

    x: 42phx;
//     >    <note{first binding here}
    x: 32phx;
//  ^error{Duplicated property binding}
    width: 12phx;
//         >    <note{first binding here}
    width <=> self.height;
//  >   <error{Duplicated property binding}

    not_exist <=> 12phx;
//  >       <error{Unknown property not-exist in Rectangle}

    property <int> foo: 12;
//                      > <note{first binding here}
    foo: 13;
//  > <error{Duplicated property binding}


}
