// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0


SubElement := Rectangle {
//         ><warning{':=' to declare a component is deprecated. The new syntax declare components with 'component MyComponent {'. Read the documentation for more info}

    foo := Rectangle {
        background: yellow;
        hello := Rectangle {}
//               >        <note{first use of this id}
//               >        <^note{first use of this id}
    }

    unique := Rectangle {
        background: yellow;
        world := Rectangle {}
//               >        <note{first use of this id}
    }

    if (true) : hello := Rectangle {
//                       >        <error{duplicated element id 'hello'}
        world := Rectangle { }
//               >        <error{duplicated element id 'world'}
    }

    hello := Rectangle {}
//           >        <error{duplicated element id 'hello'}
}

export TestCase := Rectangle {
//              ><warning{':=' to declare a component is deprecated. The new syntax declare components with 'component MyComponent {'. Read the documentation for more info}

    unique := Rectangle {
        foo := SubElement { }
//             >         <note{first use of this id}
    }

    bar := TouchArea {}
//         >        <note{first use of this id}

    Rectangle {
        foo := Text {}
//             >   <error{duplicated element id 'foo'}
        bar := Text {}
//             >   <error{duplicated element id 'bar'}
    }
}
